name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache SBT
        uses: actions/cache@v2
        with:
            path: |
                ~/.ivy2/cache
                ~/.sbt
            key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Test
        run: sbt  test
      - name: Assembly
        run: sbt assembly
      - name: Scalastyle
        run: sbt  scalastyle "test:scalastyle"
